# Generated by Django 4.2.2 on 2023-07-01 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('IdAutor', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Genero', models.CharField(max_length=20)),
                ('Apellido', models.CharField(max_length=100)),
                ('Fecha_nacimiento', models.DateField()),
                ('Nacionalidad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Idcategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('IdCredenciales', models.AutoField(primary_key=True, serialize=False)),
                ('Usuario', models.CharField(max_length=50)),
                ('Contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('idEditorial', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=254)),
                ('Pais', models.CharField(max_length=50)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('IdEncargado', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=254)),
                ('IdCredenciales', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.credenciales')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('IdEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('DNI', models.CharField(max_length=20)),
                ('Direccion', models.CharField(max_length=200)),
                ('Telefono', models.CharField(max_length=20)),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('IdLibro', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('ISBN', models.CharField(max_length=20)),
                ('Año_publicacion', models.PositiveIntegerField()),
                ('Disponibilidad', models.BooleanField(default=True)),
                ('Autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria')),
                ('Editorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.editorial')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('IdPrestamo', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPrestamo', models.DateField()),
                ('FechaDevolucion', models.DateField()),
                ('IdEncargado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.encargado')),
                ('IdEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.estudiante')),
                ('IdLibro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.libro')),
            ],
        ),
        migrations.CreateModel(
            name='Penalizacion',
            fields=[
                ('IdPenalizacion', models.AutoField(primary_key=True, serialize=False)),
                ('Falseecha_inicio', models.DateField()),
                ('Fecha_final', models.DateField()),
                ('Estado', models.CharField(max_length=50)),
                ('IdEstudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('IdDevolucion', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha_entrega', models.DateField()),
                ('Estado', models.CharField(max_length=50)),
                ('IdPrestamo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.prestamo')),
            ],
        ),
    ]
