# Generated by Django 4.2.3 on 2023-07-04 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='Genero',
            field=models.CharField(max_length=100),
        ),
    ]
