# Generated by Django 4.0 on 2023-07-06 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_alter_autor_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='Disponibilidad',
        ),
        migrations.AddField(
            model_name='libro',
            name='Cantidad',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
